/**
 * Services seed — keyed by category slug for easy insertion
 * Add new services by adding entries under the right category key.
 */
const servicesByCategorySlug = {
  'salon-women': [
    {
      name: 'Full Arms + Legs Waxing (Rica)',
      slug: 'rica-waxing-arms-legs',
      shortDescription: 'Premium Rica roll-on wax for smooth, long-lasting results',
      basePrice: 649,
      durationMinutes: 60,
      whatIsIncluded: ['Full arms waxing', 'Full legs waxing', 'Post-wax lotion'],
      whatIsNotIncluded: ['Underarms', 'Bikini wax'],
      isFeatured: true,
      isPopular: true,
      tags: ['waxing', 'rica', 'salon'],
      packages: [
        { name: 'Basic', description: 'Honey wax', price: 399, durationMinutes: 45, includes: ['Arms', 'Legs'] },
        { name: 'Standard', description: 'Rica roll-on wax', price: 649, durationMinutes: 60, includes: ['Full arms', 'Full legs', 'Post-wax lotion'], isPopular: true },
        { name: 'Premium', description: 'Chocolate & Rica combo', price: 849, durationMinutes: 75, includes: ['Full arms', 'Full legs', 'Underarms', 'Post-wax oil treatment'] },
      ],
      cityPricing: [
        { city: 'Mumbai', price: 699 }, { city: 'Delhi', price: 649 }, { city: 'Bangalore', price: 649 }, { city: 'Hyderabad', price: 599 },
      ],
    },
    {
      name: 'Gold Facial',
      slug: 'gold-facial',
      shortDescription: 'Anti-aging gold facial for radiant, youthful skin',
      basePrice: 799,
      durationMinutes: 60,
      whatIsIncluded: ['Cleansing', 'Scrubbing', 'Gold mask', 'Massage', 'Moisturiser'],
      whatIsNotIncluded: ['Hair removal', 'Threading'],
      isFeatured: true,
      tags: ['facial', 'gold', 'anti-aging'],
      packages: [
        { name: 'Basic', description: 'Fruit facial', price: 549, durationMinutes: 45, includes: ['Cleansing', 'Fruit mask', 'Moisturiser'] },
        { name: 'Standard', description: 'Gold facial', price: 799, durationMinutes: 60, includes: ['Cleansing', 'Scrub', 'Gold mask', 'Massage', 'Moisturiser'], isPopular: true },
        { name: 'Premium', description: 'HydraGlo Hydra Facial', price: 2499, durationMinutes: 90, includes: ['Cleansing', 'Exfoliation', 'Hydra infusion', 'LED therapy', 'SPF moisturiser'] },
      ],
    },
    {
      name: 'Luxury Pedicure',
      slug: 'luxury-pedicure',
      shortDescription: 'O3+ spa pedicure with scrub, mask & massage',
      basePrice: 699,
      durationMinutes: 60,
      whatIsIncluded: ['Soaking', 'Scrubbing', 'O3+ mask', 'Foot massage', 'Nail trim & paint'],
      isFeatured: false, isPopular: true,
      tags: ['pedicure', 'spa', 'nails'],
      packages: [
        { name: 'Classic', description: 'Classic pedicure', price: 399, durationMinutes: 40, includes: ['Soak', 'File', 'Cut', 'Polish'] },
        { name: 'Luxury', description: 'O3+ spa pedicure', price: 699, durationMinutes: 60, includes: ['Soak', 'Scrub', 'O3+ mask', 'Massage', 'Polish'], isPopular: true },
      ],
    },
    {
      name: 'Bridal Makeup',
      slug: 'bridal-makeup',
      shortDescription: 'HD bridal makeup by expert artists',
      basePrice: 3499,
      durationMinutes: 120,
      whatIsIncluded: ['HD foundation', 'Eye makeup', 'Contouring', 'Setting spray', 'False lashes'],
      isFeatured: true,
      tags: ['makeup', 'bridal', 'event'],
    },
    {
      name: 'Eyebrow & Upper Lip Threading',
      slug: 'threading-eyebrow-lip',
      shortDescription: 'Quick precision threading for eyebrows & upper lip',
      basePrice: 99,
      durationMinutes: 20,
      whatIsIncluded: ['Eyebrow threading', 'Upper lip threading'],
      isPopular: true,
      tags: ['threading', 'eyebrow', 'quick'],
    },
    {
      name: 'Classic Manicure',
      slug: 'classic-manicure',
      shortDescription: 'Nail shaping, cuticle care & polish for soft hands',
      basePrice: 399,
      durationMinutes: 40,
      whatIsIncluded: ['Soaking', 'Cuticle care', 'Massage', 'Nail polish'],
      tags: ['manicure', 'nails'],
    },
    {
      name: 'Hair Spa with Keratin Protein',
      slug: 'hair-spa-keratin',
      shortDescription: 'Deep conditioning hair spa for smooth, frizz-free hair',
      basePrice: 899,
      durationMinutes: 60,
      whatIsIncluded: ['Hair wash', 'Keratin protein mask', 'Steam', 'Blow dry'],
      isPopular: true,
      tags: ['hair-spa', 'keratin', 'conditioning'],
    },
    {
      name: 'Global Hair Colour (Ammonia-Free)',
      slug: 'global-hair-colour',
      shortDescription: 'Full-length ammonia-free colour for grey coverage or a fresh shade',
      basePrice: 1999,
      durationMinutes: 90,
      whatIsIncluded: ['Ammonia-free colour application', 'Conditioning wash', 'Blow dry'],
      tags: ['hair-colour', 'global-colour'],
      packages: [
        { name: 'Root Touch-up', price: 999, durationMinutes: 45, includes: ['Root colour application', 'Wash'] },
        { name: 'Global Colour', price: 1999, durationMinutes: 90, includes: ['Full-length colour', 'Conditioning', 'Blow dry'], isPopular: true },
      ],
    },
    {
      name: 'Keratin Hair Smoothening',
      slug: 'keratin-smoothening',
      shortDescription: 'Long-lasting smoothening treatment for silky, manageable hair',
      basePrice: 2999,
      durationMinutes: 150,
      whatIsIncluded: ['Hair wash', 'Keratin application', 'Straightening', 'Blow dry'],
      isFeatured: true,
      tags: ['keratin', 'smoothening', 'straightening'],
    },
    {
      name: 'Party Makeup with Saree Draping',
      slug: 'party-makeup-draping',
      shortDescription: 'HD party makeup with professional saree draping',
      basePrice: 1499,
      durationMinutes: 75,
      whatIsIncluded: ['HD makeup', 'Eye makeup', 'Saree draping', 'Hairstyling'],
      tags: ['makeup', 'party', 'draping'],
    },
    {
      name: 'Bridal Mehendi Design',
      slug: 'bridal-mehendi',
      shortDescription: 'Intricate bridal henna design for hands & feet',
      basePrice: 2499,
      durationMinutes: 120,
      whatIsIncluded: ['Bridal hand design', 'Feet design', 'Natural henna cone'],
      tags: ['mehendi', 'henna', 'bridal'],
    },
    {
      name: 'Body Polishing & De-Tan',
      slug: 'body-polishing-detan',
      shortDescription: 'Full body scrub, de-tan pack & moisturising polish',
      basePrice: 1299,
      durationMinutes: 60,
      whatIsIncluded: ['Body scrub', 'De-tan pack', 'Moisturising massage'],
      tags: ['body-polishing', 'de-tan', 'spa'],
    },
  ],

  'salon-men': [
    {
      name: 'Haircut + Beard Styling',
      slug: 'haircut-beard',
      shortDescription: 'Professional cut & beard trim at home',
      basePrice: 449,
      durationMinutes: 45,
      whatIsIncluded: ['Haircut', 'Beard trim', 'Styling', 'Head wash'],
      isFeatured: true, isPopular: true,
      tags: ['haircut', 'beard', 'grooming'],
      packages: [
        { name: 'Haircut Only', price: 299, durationMinutes: 30, includes: ['Haircut', 'Styling'] },
        { name: 'Haircut + Beard', price: 449, durationMinutes: 45, includes: ['Haircut', 'Beard trim', 'Styling'], isPopular: true },
        { name: 'Full Grooming', price: 699, durationMinutes: 60, includes: ['Haircut', 'Beard', 'D-Tan cleanup', 'Head massage'] },
      ],
    },
    {
      name: 'D-Tan Facial (Men)',
      slug: 'men-dtan-facial',
      shortDescription: 'Remove tan & refresh skin with expert facial',
      basePrice: 549,
      durationMinutes: 45,
      whatIsIncluded: ['Cleansing', 'D-Tan pack', 'Massage', 'Moisturiser'],
      tags: ['facial', 'd-tan', 'men'],
    },
    {
      name: 'Hair Colour (Men)',
      slug: 'men-hair-colour',
      shortDescription: 'Grey coverage or fresh shade hair colour for men',
      basePrice: 399,
      durationMinutes: 30,
      tags: ['hair-colour', 'men'],
    },
    {
      name: 'Head Massage & Champi',
      slug: 'head-massage-champi',
      shortDescription: 'Traditional oil head massage for stress relief',
      basePrice: 349,
      durationMinutes: 30,
      whatIsIncluded: ['Oil selection', 'Head & shoulder massage'],
      isPopular: true,
      tags: ['massage', 'champi', 'relaxation'],
    },
    {
      name: 'Classic Shave',
      slug: 'classic-shave',
      shortDescription: 'Hot towel classic shave for a clean, smooth finish',
      basePrice: 199,
      durationMinutes: 20,
      tags: ['shave', 'grooming'],
    },
    {
      name: 'Hair Spa for Men',
      slug: 'men-hair-spa',
      shortDescription: 'Deep conditioning spa for dry, damaged hair',
      basePrice: 599,
      durationMinutes: 45,
      whatIsIncluded: ['Hair wash', 'Conditioning mask', 'Head massage'],
      tags: ['hair-spa', 'men', 'conditioning'],
    },
    {
      name: 'Beard Colour & Styling',
      slug: 'beard-colour-styling',
      shortDescription: 'Beard colour touch-up with expert styling',
      basePrice: 449,
      durationMinutes: 30,
      tags: ['beard', 'colour', 'styling'],
    },
    {
      name: 'Body Massage for Men',
      slug: 'men-body-massage',
      shortDescription: 'Full body relaxation massage at home',
      basePrice: 799,
      durationMinutes: 60,
      isPopular: true,
      tags: ['massage', 'men', 'relaxation'],
    },
  ],

  'spa-massage': [
    {
      name: 'Swedish Massage',
      slug: 'swedish-massage',
      shortDescription: 'Full-body relaxation with gentle long strokes',
      basePrice: 849,
      durationMinutes: 60,
      whatIsIncluded: ['Full body massage (60 min)', 'Aromatherapy oil', 'Hot towel finish'],
      isFeatured: true, isPopular: true,
      tags: ['massage', 'swedish', 'relaxation'],
      packages: [
        { name: '60 min', price: 849, durationMinutes: 60, includes: ['Full body', 'Aroma oil'] },
        { name: '90 min', price: 1199, durationMinutes: 90, includes: ['Full body + head massage', 'Aroma oil', 'Hot towel'], isPopular: true },
      ],
    },
    {
      name: 'Deep Tissue Massage',
      slug: 'deep-tissue-massage',
      shortDescription: 'Targeted muscle therapy for pain relief',
      basePrice: 999,
      durationMinutes: 60,
      isFeatured: false, isPopular: true,
      tags: ['massage', 'deep-tissue', 'therapy'],
    },
    {
      name: 'Couple Spa',
      slug: 'couple-spa',
      shortDescription: '2 therapists, simultaneous session for couples',
      basePrice: 1799,
      durationMinutes: 60,
      isFeatured: true,
      tags: ['spa', 'couple', 'romantic'],
    },
    {
      name: 'Thai Massage',
      slug: 'thai-massage',
      shortDescription: 'Traditional stretch-based massage to relieve stiffness',
      basePrice: 1099,
      durationMinutes: 60,
      tags: ['massage', 'thai', 'stretch'],
    },
    {
      name: 'Aromatherapy Massage',
      slug: 'aromatherapy-massage',
      shortDescription: 'Essential oil massage for deep relaxation',
      basePrice: 949,
      durationMinutes: 60,
      isPopular: true,
      tags: ['massage', 'aromatherapy', 'relaxation'],
    },
    {
      name: 'Foot Reflexology',
      slug: 'foot-reflexology',
      shortDescription: 'Pressure-point foot massage to relieve fatigue',
      basePrice: 599,
      durationMinutes: 45,
      tags: ['massage', 'reflexology', 'foot'],
    },
    {
      name: 'Head, Neck & Shoulder Massage',
      slug: 'head-neck-shoulder-massage',
      shortDescription: 'Quick massage to release neck & shoulder tension',
      basePrice: 499,
      durationMinutes: 30,
      tags: ['massage', 'neck', 'shoulder'],
    },
    {
      name: 'Prenatal Massage',
      slug: 'prenatal-massage',
      shortDescription: 'Gentle, safe massage designed for expecting mothers',
      basePrice: 999,
      durationMinutes: 60,
      whatIsIncluded: ['Certified prenatal therapist', 'Safe positioning', 'Light aroma oil'],
      tags: ['massage', 'prenatal', 'pregnancy'],
    },
  ],

  'home-cleaning': [
    {
      name: 'Deep Home Cleaning',
      slug: 'deep-home-cleaning',
      shortDescription: 'Complete home deep clean by trained professionals',
      basePrice: 1499,
      durationMinutes: 180,
      whatIsIncluded: ['All rooms sweep & mop', 'Kitchen surface clean', 'Bathroom scrub', 'Fans & switchboards', 'Window sills'],
      whatIsNotIncluded: ['Sofa/carpet cleaning', 'Utensil washing'],
      isFeatured: true, isPopular: true,
      tags: ['cleaning', 'deep-clean', 'home'],
      packages: [
        { name: '1 BHK', price: 1499, durationMinutes: 120, includes: ['1 bedroom', '1 bathroom', 'Kitchen', 'Hall'] },
        { name: '2 BHK', price: 2199, durationMinutes: 180, includes: ['2 bedrooms', '2 bathrooms', 'Kitchen', 'Hall'], isPopular: true },
        { name: '3 BHK', price: 2999, durationMinutes: 240, includes: ['3 bedrooms', '2-3 bathrooms', 'Kitchen', 'Hall', 'Balconies'] },
      ],
      cityPricing: [
        { city: 'Mumbai', price: 1699 }, { city: 'Delhi', price: 1599 }, { city: 'Bangalore', price: 1499 },
      ],
    },
    {
      name: 'Sofa Deep Clean',
      slug: 'sofa-cleaning',
      shortDescription: 'Foam extraction sofa cleaning',
      basePrice: 499,
      durationMinutes: 60,
      isFeatured: false, isPopular: true,
      tags: ['cleaning', 'sofa', 'furniture'],
      packages: [
        { name: '2-seater', price: 499, durationMinutes: 45, includes: ['Foam extraction', 'Deodorisation'] },
        { name: '3-seater', price: 699, durationMinutes: 60, includes: ['Foam extraction', 'Stain removal', 'Deodorisation'], isPopular: true },
        { name: 'L-shape', price: 999, durationMinutes: 90, includes: ['Full foam extraction', 'Deep stain removal', 'Anti-bacterial spray'] },
      ],
    },
    {
      name: 'General Cleaning (Hourly)',
      slug: 'general-cleaning-hourly',
      shortDescription: 'Mopping, dusting & basic cleaning by the hour',
      basePrice: 299,
      durationMinutes: 60,
      isFeatured: false, isPopular: true,
      tags: ['cleaning', 'hourly', 'daily'],
      packages: [
        { name: '1 Hour', price: 299, durationMinutes: 60, includes: ['Mopping', 'Dusting'] },
        { name: '2 Hours', price: 549, durationMinutes: 120, includes: ['Mopping', 'Dusting', 'Kitchen surface', 'Bathroom quick clean'], isPopular: true },
        { name: '4 Hours', price: 999, durationMinutes: 240, includes: ['Full deep clean', 'Kitchen', 'Bathrooms', 'Dishes', 'Laundry fold'] },
      ],
    },
    {
      name: 'Full Home Disinfection',
      slug: 'home-disinfection',
      shortDescription: 'Sanitisation spray for germ-free, virus-safe homes',
      basePrice: 999,
      durationMinutes: 60,
      whatIsIncluded: ['Hospital-grade disinfectant spray', 'High-touch surface focus'],
      tags: ['disinfection', 'sanitisation', 'cleaning'],
    },
    {
      name: 'Move-in / Move-out Deep Cleaning',
      slug: 'move-in-move-out-cleaning',
      shortDescription: 'Thorough deep clean for new or vacated homes',
      basePrice: 2499,
      durationMinutes: 210,
      whatIsIncluded: ['All rooms deep clean', 'Cabinet interiors', 'Bathroom descaling', 'Kitchen degreasing'],
      isFeatured: true,
      tags: ['cleaning', 'move-in', 'move-out'],
    },
    {
      name: 'Balcony & Utility Area Cleaning',
      slug: 'balcony-utility-cleaning',
      shortDescription: 'Sweep, scrub & declutter balconies and utility spaces',
      basePrice: 399,
      durationMinutes: 45,
      tags: ['cleaning', 'balcony', 'utility'],
    },
    {
      name: 'Mattress Deep Cleaning',
      slug: 'mattress-cleaning',
      shortDescription: 'Vacuum, sanitise & stain-treat your mattress',
      basePrice: 599,
      durationMinutes: 45,
      tags: ['cleaning', 'mattress', 'sanitise'],
    },
    {
      name: 'Curtain & Blinds Cleaning',
      slug: 'curtain-blinds-cleaning',
      shortDescription: 'On-site dusting & steam cleaning for curtains and blinds',
      basePrice: 449,
      durationMinutes: 40,
      tags: ['cleaning', 'curtains', 'blinds'],
    },
  ],

  'kitchen-bathroom': [
    {
      name: 'Kitchen Deep Cleaning',
      slug: 'kitchen-deep-cleaning',
      shortDescription: 'Degreasing, tile scrub & platform sanitisation',
      basePrice: 799,
      durationMinutes: 90,
      whatIsIncluded: ['Platform & tile degreasing', 'Chimney exterior wipe', 'Sink descaling', 'Cabinet exteriors'],
      isFeatured: true,
      isPopular: true,
      tags: ['kitchen', 'deep-clean', 'degreasing'],
    },
    {
      name: 'Bathroom Deep Cleaning',
      slug: 'bathroom-deep-cleaning',
      shortDescription: 'Tile, tap & commode descaling for a sparkling bathroom',
      basePrice: 499,
      durationMinutes: 60,
      whatIsIncluded: ['Tile & grout scrub', 'Commode descaling', 'Tap & mirror shine'],
      isPopular: true,
      tags: ['bathroom', 'deep-clean', 'descaling'],
      packages: [
        { name: '1 Bathroom', price: 499, durationMinutes: 60, includes: ['Tile scrub', 'Commode descaling', 'Fittings shine'] },
        { name: '2 Bathrooms', price: 899, durationMinutes: 100, includes: ['Tile scrub', 'Commode descaling', 'Fittings shine'], isPopular: true },
      ],
    },
    {
      name: 'Chimney & Exhaust Cleaning',
      slug: 'chimney-exhaust-cleaning',
      shortDescription: 'Degreasing & filter cleaning for kitchen chimneys',
      basePrice: 599,
      durationMinutes: 60,
      tags: ['kitchen', 'chimney', 'exhaust'],
    },
    {
      name: 'Overhead Water Tank Cleaning',
      slug: 'water-tank-cleaning',
      shortDescription: 'Sludge removal & sanitisation for overhead tanks',
      basePrice: 699,
      durationMinutes: 60,
      tags: ['water-tank', 'cleaning', 'sanitisation'],
    },
    {
      name: 'Modular Kitchen Cabinet Cleaning',
      slug: 'modular-kitchen-cleaning',
      shortDescription: 'Interior & exterior cleaning for modular kitchen units',
      basePrice: 899,
      durationMinutes: 90,
      tags: ['kitchen', 'modular', 'cabinets'],
    },
  ],

  'ac-service': [
    {
      name: 'Power Saver AC Service',
      slug: 'ac-power-saver',
      shortDescription: 'Energy-efficient AC service in 45 minutes',
      basePrice: 549,
      durationMinutes: 45,
      whatIsIncluded: ['Filter clean', 'Coil wash', 'Drain check', 'Performance test'],
      isFeatured: true, isPopular: true,
      tags: ['ac', 'service', 'repair'],
      packages: [
        { name: 'Power Saver', price: 549, durationMinutes: 45, includes: ['Filter clean', 'Coil wash', 'Drain check'] },
        { name: 'Jet Deep Clean', price: 699, durationMinutes: 60, includes: ['Filter clean', 'Deep coil wash', 'Anti-bacterial spray', 'Gas check'], isPopular: true },
        { name: 'Anti-Rust Deep Clean', price: 849, durationMinutes: 75, includes: ['Deep coil wash', 'Anti-rust treatment', 'Gas top-up', 'Full report'] },
      ],
    },
    {
      name: 'Split AC Installation',
      slug: 'split-ac-installation',
      shortDescription: 'Professional installation for new split AC units',
      basePrice: 1499,
      durationMinutes: 90,
      whatIsIncluded: ['Wall mounting', 'Piping & wiring', 'Gas charging check'],
      tags: ['ac', 'installation', 'split-ac'],
    },
    {
      name: 'Window AC Service',
      slug: 'window-ac-service',
      shortDescription: 'Filter clean, coil wash & performance check for window ACs',
      basePrice: 449,
      durationMinutes: 40,
      tags: ['ac', 'window-ac', 'service'],
    },
    {
      name: 'AC Gas Refill (Split)',
      slug: 'ac-gas-refill',
      shortDescription: 'Refrigerant gas top-up for weak cooling',
      basePrice: 2499,
      durationMinutes: 60,
      isFeatured: true,
      tags: ['ac', 'gas-refill', 'cooling'],
    },
    {
      name: 'AC Uninstallation',
      slug: 'ac-uninstallation',
      shortDescription: 'Safe removal of AC unit before relocation',
      basePrice: 499,
      durationMinutes: 30,
      tags: ['ac', 'uninstallation', 'relocation'],
    },
    {
      name: 'AC No-Cooling Repair',
      slug: 'ac-no-cooling-repair',
      shortDescription: 'Diagnosis & repair for ACs blowing warm air',
      basePrice: 349,
      durationMinutes: 45,
      isPopular: true,
      tags: ['ac', 'repair', 'no-cooling'],
    },
  ],

  'appliance-repair': [
    {
      name: 'Refrigerator Repair',
      slug: 'refrigerator-repair',
      shortDescription: 'All brands refrigerator repair at home',
      basePrice: 399,
      durationMinutes: 60,
      isFeatured: false, isPopular: true,
      tags: ['appliance', 'refrigerator', 'repair'],
    },
    {
      name: 'Washing Machine Repair',
      slug: 'washing-machine-repair',
      shortDescription: 'Front & top load washing machine repair',
      basePrice: 399,
      durationMinutes: 60,
      tags: ['appliance', 'washing-machine', 'repair'],
    },
    {
      name: 'Geyser / Water Heater Repair',
      slug: 'geyser-repair',
      shortDescription: 'Geyser repair & installation',
      basePrice: 349,
      durationMinutes: 45,
      tags: ['appliance', 'geyser', 'repair'],
    },
    {
      name: 'Microwave Repair',
      slug: 'microwave-repair',
      shortDescription: 'All brands microwave & OTG repair at home',
      basePrice: 349,
      durationMinutes: 45,
      tags: ['appliance', 'microwave', 'repair'],
    },
    {
      name: 'Kitchen Chimney Repair',
      slug: 'chimney-repair',
      shortDescription: 'Motor, suction & filter repair for kitchen chimneys',
      basePrice: 399,
      durationMinutes: 45,
      tags: ['appliance', 'chimney', 'repair'],
    },
    {
      name: 'RO Water Purifier Service',
      slug: 'ro-water-purifier-service',
      shortDescription: 'Filter change & full service for RO purifiers',
      basePrice: 499,
      durationMinutes: 45,
      isPopular: true,
      tags: ['appliance', 'water-purifier', 'ro-service'],
    },
    {
      name: 'TV Repair',
      slug: 'tv-repair',
      shortDescription: 'LED/LCD TV diagnosis & repair at home',
      basePrice: 449,
      durationMinutes: 45,
      tags: ['appliance', 'tv', 'repair'],
    },
    {
      name: 'Air Cooler Service',
      slug: 'air-cooler-service',
      shortDescription: 'Pump, pad & motor check before summer season',
      basePrice: 349,
      durationMinutes: 40,
      tags: ['appliance', 'air-cooler', 'service'],
    },
  ],

  'plumbing': [
    {
      name: 'Leaky Tap / Pipe Repair',
      slug: 'tap-pipe-repair',
      shortDescription: 'Fix leaky taps & pipes instantly',
      basePrice: 249,
      durationMinutes: 30,
      isFeatured: false, isPopular: true,
      tags: ['plumbing', 'tap', 'repair'],
    },
    {
      name: 'Toilet Flush Repair',
      slug: 'toilet-flush-repair',
      shortDescription: 'Flush tank & cistern repair',
      basePrice: 299,
      durationMinutes: 30,
      tags: ['plumbing', 'toilet', 'repair'],
    },
    {
      name: 'Wash Basin Installation',
      slug: 'wash-basin-installation',
      shortDescription: 'New wash basin fitting with leak-proof sealing',
      basePrice: 449,
      durationMinutes: 45,
      tags: ['plumbing', 'wash-basin', 'installation'],
    },
    {
      name: 'Overhead Tank Installation',
      slug: 'water-tank-installation',
      shortDescription: 'New overhead water tank setup & pipe connection',
      basePrice: 1499,
      durationMinutes: 120,
      tags: ['plumbing', 'water-tank', 'installation'],
    },
    {
      name: 'Bathroom Fitting Installation',
      slug: 'bathroom-fitting-installation',
      shortDescription: 'Shower, tap & fixture installation for bathrooms',
      basePrice: 599,
      durationMinutes: 60,
      tags: ['plumbing', 'bathroom', 'fittings'],
    },
    {
      name: 'Drainage & Sewage Line Cleaning',
      slug: 'drainage-sewage-cleaning',
      shortDescription: 'Machine-assisted unclogging for blocked drains',
      basePrice: 799,
      durationMinutes: 60,
      isPopular: true,
      tags: ['plumbing', 'drainage', 'unclogging'],
    },
    {
      name: 'Water Motor / Pump Repair',
      slug: 'water-motor-pump-repair',
      shortDescription: 'Diagnosis & repair for water motors and pumps',
      basePrice: 449,
      durationMinutes: 45,
      tags: ['plumbing', 'motor', 'pump'],
    },
  ],

  electrical: [
    {
      name: 'Switch & Socket Repair',
      slug: 'switch-socket-repair',
      shortDescription: 'Replace faulty switches, sockets & plate covers',
      basePrice: 149,
      durationMinutes: 20,
      isPopular: true,
      tags: ['electrical', 'switch', 'socket'],
    },
    {
      name: 'Ceiling Fan Installation',
      slug: 'ceiling-fan-installation',
      shortDescription: 'Safe mounting & wiring for new ceiling fans',
      basePrice: 249,
      durationMinutes: 30,
      isFeatured: true,
      tags: ['electrical', 'fan', 'installation'],
    },
    {
      name: 'MCB & Fuse Repair',
      slug: 'mcb-fuse-repair',
      shortDescription: 'Fix tripping MCBs & blown fuses',
      basePrice: 299,
      durationMinutes: 30,
      tags: ['electrical', 'mcb', 'fuse'],
    },
    {
      name: 'Full Home Wiring',
      slug: 'full-home-wiring',
      shortDescription: 'Complete concealed wiring for new or renovated homes',
      basePrice: 3499,
      durationMinutes: 240,
      whatIsIncluded: ['Wiring layout planning', 'Concealed wiring', 'Switchboard fitting'],
      tags: ['electrical', 'wiring', 'home'],
    },
    {
      name: 'Inverter & Stabilizer Installation',
      slug: 'inverter-stabilizer-installation',
      shortDescription: 'Setup & wiring for inverters and voltage stabilizers',
      basePrice: 499,
      durationMinutes: 45,
      tags: ['electrical', 'inverter', 'stabilizer'],
    },
    {
      name: 'Doorbell & Intercom Installation',
      slug: 'doorbell-intercom-installation',
      shortDescription: 'Wired or wireless doorbell and intercom setup',
      basePrice: 299,
      durationMinutes: 30,
      tags: ['electrical', 'doorbell', 'intercom'],
    },
  ],

  carpentry: [
    {
      name: 'Furniture Assembly',
      slug: 'furniture-assembly',
      shortDescription: 'Assembly for flat-pack beds, wardrobes & tables',
      basePrice: 399,
      durationMinutes: 60,
      isPopular: true,
      tags: ['carpentry', 'assembly', 'furniture'],
    },
    {
      name: 'Door & Window Repair',
      slug: 'door-window-repair',
      shortDescription: 'Fix jammed doors, loose hinges & window frames',
      basePrice: 349,
      durationMinutes: 45,
      tags: ['carpentry', 'door', 'window'],
    },
    {
      name: 'Bed & Wardrobe Repair',
      slug: 'bed-wardrobe-repair',
      shortDescription: 'Repair for loose joints, drawers & wardrobe shutters',
      basePrice: 449,
      durationMinutes: 60,
      tags: ['carpentry', 'bed', 'wardrobe'],
    },
    {
      name: 'Curtain Rod Installation',
      slug: 'curtain-rod-installation',
      shortDescription: 'Wall-mounted curtain rod & bracket fitting',
      basePrice: 249,
      durationMinutes: 30,
      tags: ['carpentry', 'curtain-rod', 'installation'],
    },
    {
      name: 'Modular Furniture Repair',
      slug: 'modular-furniture-repair',
      shortDescription: 'Repair for modular kitchen & wardrobe fittings',
      basePrice: 599,
      durationMinutes: 60,
      tags: ['carpentry', 'modular', 'repair'],
    },
  ],

  'pest-control': [
    {
      name: 'Full Home Pest Control',
      slug: 'full-home-pest-control',
      shortDescription: 'Cockroach, ant & rodent treatment',
      basePrice: 999,
      durationMinutes: 60,
      whatIsIncluded: ['Gel treatment', 'Spray treatment', '30-day warranty'],
      isFeatured: true, isPopular: true,
      tags: ['pest', 'cockroach', 'treatment'],
      packages: [
        { name: '1 BHK', price: 999, durationMinutes: 60, includes: ['Cockroach gel', 'Ant treatment', '30-day warranty'] },
        { name: '2 BHK', price: 1299, durationMinutes: 75, includes: ['Full home treatment', '60-day warranty'], isPopular: true },
        { name: 'Annual Plan', price: 3999, durationMinutes: 60, includes: ['4 visits/year', 'All pests', 'Priority support'] },
      ],
    },
    {
      name: 'Cockroach Control',
      slug: 'cockroach-control',
      shortDescription: 'Gel-based cockroach treatment with lasting effect',
      basePrice: 599,
      durationMinutes: 45,
      isPopular: true,
      tags: ['pest', 'cockroach', 'gel-treatment'],
    },
    {
      name: 'Termite (Deemak) Treatment',
      slug: 'termite-treatment',
      shortDescription: 'Anti-termite treatment for walls, wood & furniture',
      basePrice: 2999,
      durationMinutes: 120,
      whatIsIncluded: ['Chemical barrier treatment', 'Wood injection', '1-year warranty'],
      isFeatured: true,
      tags: ['pest', 'termite', 'treatment'],
    },
    {
      name: 'Bed Bug Treatment',
      slug: 'bed-bug-treatment',
      shortDescription: 'Targeted spray treatment for mattresses & furniture',
      basePrice: 1299,
      durationMinutes: 60,
      tags: ['pest', 'bed-bug', 'treatment'],
    },
    {
      name: 'Mosquito Fogging',
      slug: 'mosquito-fogging',
      shortDescription: 'Fogging treatment for mosquito-prone homes',
      basePrice: 699,
      durationMinutes: 45,
      tags: ['pest', 'mosquito', 'fogging'],
    },
    {
      name: 'Rodent Control',
      slug: 'rodent-control',
      shortDescription: 'Trap placement & rodent-proofing for homes',
      basePrice: 899,
      durationMinutes: 45,
      tags: ['pest', 'rodent', 'trap'],
    },
  ],

  painting: [
    {
      name: 'Interior Wall Painting',
      slug: 'interior-wall-painting',
      shortDescription: 'Full interior painting with premium emulsion',
      basePrice: 3999,
      durationMinutes: 480,
      whatIsIncluded: ['Wall putty & prep', 'Primer coat', '2 coats premium emulsion'],
      isFeatured: true,
      tags: ['painting', 'interior', 'wall'],
    },
    {
      name: 'Exterior Wall Painting',
      slug: 'exterior-wall-painting',
      shortDescription: 'Weatherproof exterior painting for homes',
      basePrice: 5999,
      durationMinutes: 480,
      whatIsIncluded: ['Surface cleaning', 'Crack filling', 'Weatherproof paint'],
      tags: ['painting', 'exterior', 'weatherproof'],
    },
    {
      name: 'Single Room Painting',
      slug: 'single-room-painting',
      shortDescription: 'Quick refresh painting for one room',
      basePrice: 1499,
      durationMinutes: 240,
      isPopular: true,
      tags: ['painting', 'room', 'quick'],
    },
    {
      name: 'Waterproofing & Painting',
      slug: 'waterproofing-painting',
      shortDescription: 'Leak-proofing treatment combined with fresh paint',
      basePrice: 4999,
      durationMinutes: 360,
      tags: ['painting', 'waterproofing', 'leak-proof'],
    },
    {
      name: 'Wood Polishing',
      slug: 'wood-polishing',
      shortDescription: 'Melamine or PU polish for doors & furniture',
      basePrice: 999,
      durationMinutes: 90,
      tags: ['painting', 'wood-polish', 'furniture'],
    },
  ],

  'laundry-daily': [
    {
      name: 'Wash & Fold (per kg)',
      slug: 'wash-and-fold',
      shortDescription: 'Everyday laundry washed, dried & neatly folded',
      basePrice: 79,
      durationMinutes: 20,
      isPopular: true,
      tags: ['laundry', 'wash', 'fold'],
    },
    {
      name: 'Wash & Iron (per kg)',
      slug: 'wash-and-iron',
      shortDescription: 'Laundry washed and pressed, ready to wear',
      basePrice: 99,
      durationMinutes: 20,
      tags: ['laundry', 'wash', 'iron'],
    },
    {
      name: 'Dry Cleaning Pickup',
      slug: 'dry-cleaning-pickup',
      shortDescription: 'Doorstep pickup & drop for dry cleaning',
      basePrice: 149,
      durationMinutes: 20,
      tags: ['laundry', 'dry-clean', 'pickup'],
    },
    {
      name: 'Steam Ironing (per 10 clothes)',
      slug: 'steam-ironing',
      shortDescription: 'Crease-free steam ironing at your doorstep',
      basePrice: 199,
      durationMinutes: 30,
      isPopular: true,
      tags: ['laundry', 'ironing', 'steam'],
    },
    {
      name: 'Daily Cook / Helper Booking',
      slug: 'daily-cook-helper',
      shortDescription: 'Book a trained helper for daily cooking & chores',
      basePrice: 499,
      durationMinutes: 60,
      tags: ['daily-help', 'cook', 'helper'],
    },
  ],

  'car-care': [
    {
      name: 'Car Foam Wash',
      slug: 'car-foam-wash',
      shortDescription: 'Premium foam car wash at your doorstep',
      basePrice: 399,
      durationMinutes: 45,
      isFeatured: true, isPopular: true,
      tags: ['car', 'wash', 'cleaning'],
      packages: [
        { name: 'Basic Wash', price: 399, durationMinutes: 30, includes: ['Exterior foam wash', 'Wipe dry'] },
        { name: 'Interior + Exterior', price: 699, durationMinutes: 60, includes: ['Foam wash', 'Interior vacuum', 'Dashboard wipe'], isPopular: true },
        { name: 'Full Detail', price: 1499, durationMinutes: 120, includes: ['Full foam wash', 'Interior deep clean', 'Tyre polish', 'Wax coating'] },
      ],
    },
    {
      name: 'Car Interior Detailing',
      slug: 'car-interior-detailing',
      shortDescription: 'Deep vacuum, shampoo & dashboard detailing',
      basePrice: 999,
      durationMinutes: 90,
      isPopular: true,
      tags: ['car', 'interior', 'detailing'],
    },
    {
      name: 'Car Ceramic Coating',
      slug: 'car-ceramic-coating',
      shortDescription: 'Long-lasting ceramic coating for showroom shine',
      basePrice: 6999,
      durationMinutes: 240,
      isFeatured: true,
      tags: ['car', 'ceramic-coating', 'premium'],
    },
    {
      name: 'Bike Wash',
      slug: 'bike-wash',
      shortDescription: 'Doorstep foam wash for two-wheelers',
      basePrice: 199,
      durationMinutes: 20,
      tags: ['bike', 'wash', 'two-wheeler'],
    },
    {
      name: 'Car Polish & Wax',
      slug: 'car-polish-wax',
      shortDescription: 'Scratch removal polish with protective wax coat',
      basePrice: 799,
      durationMinutes: 60,
      tags: ['car', 'polish', 'wax'],
    },
  ],
};

const { categories: categoryImages } = require('./image-assets.json');

for (const [slug, services] of Object.entries(servicesByCategorySlug)) {
  const pool = categoryImages[slug] || [];
  services.forEach((svc, i) => {
    if (pool.length) {
      svc.images = [...new Set([pool[i % pool.length], pool[(i + 1) % pool.length]])];
    }
  });
}

module.exports = servicesByCategorySlug;
