'use strict';
/**
 * Organic property seed data for the realestate module.
 *
 * The first 8 entries keep the exact `propertyID`s that were already live in
 * production (from the original scripts/seed.js) — their `uploadedPaths` here
 * point at real images now uploaded to the `realistanimages` S3 bucket, fixing
 * the broken/never-uploaded keys the old seed referenced. Everything after that
 * is new inventory across 6 cities.
 */

const { PROPERTY_IMG, img } = require('./image-assets');

const now = () => +new Date();
const daysAgo = (n) => now() - n * 86400000;

module.exports = [
    // ─── Existing listings (image paths fixed) ────────────────────────────────
    {
        propertyID: 'brigade-insignia-3-bhk-jp-nagar-phase-2-sale-bangalore',
        title: 'Brigade Insignia', listingType: 'sale', buildingType: 'Apartment',
        propertyType: 'Residential', possessionStatus: 'Ready To Move',
        price: '12500000', priceNumber: 12500000,
        area: '1850', areaNumber: 1850, areaCarpet: '1550', areaCarpetNumber: 1550,
        location: 'JP Nagar Phase 2', city: 'Bangalore', postalCode: '560078',
        houseType: '3 BHK', bathsType: '3', floorNumber: '8', floorNumberNumber: 8,
        towerBlock: 'A', totalFloorCount: '18', ageProperty: 'New',
        furnishingStatus: 'Semi-Furnished', facing: 'East', view: 'Garden View',
        balcony: '2', powerBackup: 'Full', flooring: 'Vitrified Tiles',
        coveredParking: 2, coveredUnParking: 1, sutableFor: 'Family',
        additionalRooms: ['Pooja Room', 'Study Room'], trasactionType: 'New Booking',
        landmarkHospital: 'Apollo Spectra 1.2 km', landmarkEducationInstitute: 'Greenwood High 800 m',
        landmarkShoppingCenter: 'Forum Mall 2 km', landmarkTransportation: 'Banashankari Metro 1.5 km',
        landmarkCommercialHub: 'Bannerghatta Road IT Corridor 3 km',
        amenitiesDetails: [{ name: 'Swimming Pool', count: 1 }, { name: 'Gym', count: 1 }, { name: 'Clubhouse', count: 1 }, { name: 'Children Play Area', count: 1 }, { name: 'Indoor Games', count: 1 }, { name: '24/7 Security', count: 1 }],
        furnishingDetails: [{ name: 'AC', count: 3 }, { name: 'Wardrobe', count: 3 }, { name: 'Modular Kitchen', count: 1 }, { name: 'Geyser', count: 2 }],
        aboutProperty: 'Premium 3 BHK apartment in Brigade Insignia with world-class amenities. Located in the heart of JP Nagar with excellent connectivity.',
        defineSizeStructure: '3 BHK with large balcony and servant quarters',
        uploadedPaths: img(PROPERTY_IMG.bangaloreBrigadeExotica), isExclusive: true, isFeatured: true,
        createAt: daysAgo(30), updatedAt: daysAgo(2),
    },
    {
        propertyID: 'birla-trimaya-2-bhk-devanahalli-sale-bangalore',
        title: 'Birla Trimaya', listingType: 'sale', buildingType: 'Apartment',
        propertyType: 'Residential', possessionStatus: 'Under Construction',
        price: '7800000', priceNumber: 7800000,
        area: '1250', areaNumber: 1250, areaCarpet: '1050', areaCarpetNumber: 1050,
        location: 'Devanahalli', city: 'Bangalore', postalCode: '562110',
        houseType: '2 BHK', bathsType: '2', floorNumber: '5', floorNumberNumber: 5,
        towerBlock: 'B', totalFloorCount: '22', ageProperty: 'New',
        furnishingStatus: 'Unfurnished', facing: 'North East', view: 'City View',
        balcony: '1', powerBackup: 'Full', flooring: 'Ceramic Tiles',
        coveredParking: 1, coveredUnParking: 0, sutableFor: 'Family',
        additionalRooms: ['Pooja Room'], trasactionType: 'New Booking',
        landmarkHospital: 'Aster CMI Hospital 5 km', landmarkEducationInstitute: 'Nitte Meenakshi Institute 3 km',
        landmarkTransportation: 'Kempegowda Airport 8 km', landmarkCommercialHub: 'Aerospace Park 4 km',
        amenitiesDetails: [{ name: 'Swimming Pool', count: 1 }, { name: 'Gym', count: 1 }, { name: 'Jogging Track', count: 1 }, { name: 'Children Play Area', count: 1 }, { name: 'Squash Court', count: 1 }],
        furnishingDetails: [],
        aboutProperty: 'Birla Trimaya offers thoughtfully designed 2 BHK homes near the international airport. RERA registered.',
        uploadedPaths: img(PROPERTY_IMG.bangalorePashminaWaterfront), isExclusive: true, isFeatured: false,
        createAt: daysAgo(25), updatedAt: daysAgo(1),
    },
    {
        propertyID: 'embassy-verde-4-bhk-sarjapur-sale-bangalore',
        title: 'Embassy Verde', listingType: 'sale', buildingType: 'Villa',
        propertyType: 'Residential', possessionStatus: 'Ready To Move',
        price: '32000000', priceNumber: 32000000,
        area: '4200', areaNumber: 4200, areaCarpet: '3800', areaCarpetNumber: 3800,
        location: 'Sarjapur Road', city: 'Bangalore', postalCode: '562125',
        houseType: '4 BHK', bathsType: '5', floorNumber: 'G', floorNumberNumber: 0,
        towerBlock: 'Villa', totalFloorCount: '3', ageProperty: 'New',
        furnishingStatus: 'Fully Furnished', facing: 'East', view: 'Golf Course View',
        balcony: '4', powerBackup: 'Full', flooring: 'Marble',
        coveredParking: 3, coveredUnParking: 1, sutableFor: 'Family',
        additionalRooms: ['Servant Quarter', 'Pooja Room', 'Study Room', 'Home Theatre'], trasactionType: 'New Booking',
        landmarkHospital: 'Narayana Health 6 km', landmarkEducationInstitute: 'Greenwood High School 2 km',
        landmarkShoppingCenter: 'Total Mall 4 km', landmarkTransportation: 'Carmelaram Railway 3 km',
        landmarkCommercialHub: 'Wipro Campus 2 km',
        amenitiesDetails: [{ name: 'Private Pool', count: 1 }, { name: 'Gym', count: 1 }, { name: 'Clubhouse', count: 1 }, { name: 'Golf Course', count: 1 }, { name: 'Tennis Court', count: 2 }, { name: 'Concierge', count: 1 }],
        furnishingDetails: [{ name: 'AC', count: 6 }, { name: 'Wardrobe', count: 6 }, { name: 'Modular Kitchen', count: 1 }, { name: 'Refrigerator', count: 2 }, { name: 'Washing Machine', count: 1 }, { name: 'Smart Home System', count: 1 }],
        aboutProperty: 'Sprawling Embassy Verde villas with private pool and golf course views. The epitome of luxury living in Bangalore.',
        uploadedPaths: img(PROPERTY_IMG.villaRoyal, PROPERTY_IMG.interiorLivingRoom1), isExclusive: true, isFeatured: true,
        createAt: daysAgo(15), updatedAt: daysAgo(0),
    },
    {
        propertyID: 'premium-2bhk-koramangala-rent-bangalore',
        title: 'Premium 2BHK in Koramangala', listingType: 'rent', buildingType: 'Apartment',
        propertyType: 'Residential', possessionStatus: 'Ready To Move',
        price: '35000', priceNumber: 35000,
        area: '1200', areaNumber: 1200, areaCarpet: '1000', areaCarpetNumber: 1000,
        location: 'Koramangala 5th Block', city: 'Bangalore', postalCode: '560095',
        houseType: '2 BHK', bathsType: '2', floorNumber: '3', floorNumberNumber: 3,
        towerBlock: '1', totalFloorCount: '6', ageProperty: '2-4',
        furnishingStatus: 'Fully Furnished', facing: 'North', view: 'Street View',
        balcony: '1', powerBackup: 'Partial', flooring: 'Vitrified Tiles',
        coveredParking: 1, coveredUnParking: 0, sutableFor: 'Family',
        additionalRooms: [], trasactionType: 'Rent',
        landmarkHospital: "St. John's Medical 1.5 km", landmarkShoppingCenter: 'Garuda Mall 2 km',
        landmarkTransportation: 'Koramangala Bus Stop 200 m',
        amenitiesDetails: [{ name: 'Gym', count: 1 }, { name: 'Lift', count: 2 }, { name: 'Security', count: 1 }],
        furnishingDetails: [{ name: 'AC', count: 2 }, { name: 'Wardrobe', count: 2 }, { name: 'Refrigerator', count: 1 }, { name: 'Washing Machine', count: 1 }],
        aboutProperty: 'Fully furnished 2BHK in the startup hub of Bangalore. Ideal for working professionals.',
        uploadedPaths: img(PROPERTY_IMG.bangaloreSalarpuriaGold), isExclusive: false, isFeatured: false,
        createAt: daysAgo(10), updatedAt: daysAgo(0),
    },
    {
        propertyID: 'lodha-world-one-4bhk-worli-sale-mumbai',
        title: 'Lodha World One', listingType: 'sale', buildingType: 'Apartment',
        propertyType: 'Residential', possessionStatus: 'Ready To Move',
        price: '85000000', priceNumber: 85000000,
        area: '3200', areaNumber: 3200, areaCarpet: '2800', areaCarpetNumber: 2800,
        location: 'Worli', city: 'Mumbai', postalCode: '400018',
        houseType: '4 BHK', bathsType: '4', floorNumber: '55', floorNumberNumber: 55,
        towerBlock: 'Tower 1', totalFloorCount: '117', ageProperty: 'New',
        furnishingStatus: 'Fully Furnished', facing: 'Sea Facing', view: 'Sea View',
        balcony: '3', powerBackup: 'Full', flooring: 'Italian Marble',
        coveredParking: 2, coveredUnParking: 0, sutableFor: 'Family',
        additionalRooms: ['Servant Quarter', 'Home Theatre', 'Pooja Room'], trasactionType: 'New Booking',
        landmarkHospital: 'Hinduja Hospital 3 km', landmarkEducationInstitute: 'Cathedral School 4 km',
        landmarkShoppingCenter: 'Palladium Mall 2 km', landmarkTransportation: 'Worli Sea Link 500 m',
        landmarkCommercialHub: 'BKC Financial District 5 km',
        amenitiesDetails: [{ name: 'Infinity Pool', count: 2 }, { name: 'Gym', count: 1 }, { name: 'Spa', count: 1 }, { name: 'Concierge', count: 1 }, { name: 'Private Cinema', count: 1 }],
        furnishingDetails: [{ name: 'AC', count: 6 }, { name: 'Wardrobe', count: 6 }, { name: 'Modular Kitchen', count: 1 }, { name: 'Smart Home', count: 1 }],
        aboutProperty: 'Sky-high luxury at Lodha World One, the tallest residential tower in India. Breathtaking sea and city views.',
        uploadedPaths: img(PROPERTY_IMG.mumbaiCrownTowerEvening, PROPERTY_IMG.interiorLivingRoom2), isExclusive: true, isFeatured: true,
        createAt: daysAgo(45), updatedAt: daysAgo(5),
    },
    {
        propertyID: 'dlf-the-crest-3bhk-dlf-5-sale-gurgaon',
        title: 'DLF The Crest', listingType: 'sale', buildingType: 'Apartment',
        propertyType: 'Residential', possessionStatus: 'Ready To Move',
        price: '38000000', priceNumber: 38000000,
        area: '2850', areaNumber: 2850, areaCarpet: '2400', areaCarpetNumber: 2400,
        location: 'DLF Phase 5', city: 'Gurgaon', postalCode: '122009',
        houseType: '3 BHK', bathsType: '4', floorNumber: '18', floorNumberNumber: 18,
        towerBlock: 'North Tower', totalFloorCount: '29', ageProperty: '0-2',
        furnishingStatus: 'Fully Furnished', facing: 'East', view: 'Golf Course View',
        balcony: '3', powerBackup: 'Full', flooring: 'Wooden',
        coveredParking: 2, coveredUnParking: 0, sutableFor: 'Family',
        additionalRooms: ['Study Room', 'Servant Quarter'], trasactionType: 'Resale',
        landmarkHospital: 'Medanta Hospital 3 km', landmarkEducationInstitute: 'The Shriram School 2 km',
        landmarkShoppingCenter: 'MGF Metropolitan Mall 4 km', landmarkTransportation: 'IFFCO Chowk Metro 3 km',
        landmarkCommercialHub: 'DLF Cyber Hub 2 km',
        amenitiesDetails: [{ name: 'Swimming Pool', count: 2 }, { name: 'Gym', count: 1 }, { name: 'Clubhouse', count: 1 }, { name: 'Golf Course', count: 1 }, { name: 'Squash Court', count: 1 }],
        furnishingDetails: [{ name: 'AC', count: 5 }, { name: 'Wardrobe', count: 5 }, { name: 'Smart Home', count: 1 }],
        aboutProperty: 'DLF The Crest — ultra-luxury residences facing the DLF Golf & Country Club. Set on 17 acres of prime land.',
        uploadedPaths: img(PROPERTY_IMG.gurgaonDlfEpitomeTower), isExclusive: true, isFeatured: true,
        createAt: daysAgo(60), updatedAt: daysAgo(7),
    },
    {
        propertyID: 'my-home-aura-3bhk-gachibowli-sale-hyderabad',
        title: 'My Home Aura', listingType: 'sale', buildingType: 'Apartment',
        propertyType: 'Residential', possessionStatus: 'Ready To Move',
        price: '11500000', priceNumber: 11500000,
        area: '1950', areaNumber: 1950, areaCarpet: '1650', areaCarpetNumber: 1650,
        location: 'Gachibowli', city: 'Hyderabad', postalCode: '500032',
        houseType: '3 BHK', bathsType: '3', floorNumber: '9', floorNumberNumber: 9,
        towerBlock: 'B', totalFloorCount: '24', ageProperty: '0-2',
        furnishingStatus: 'Semi-Furnished', facing: 'North', view: 'Lake View',
        balcony: '2', powerBackup: 'Full', flooring: 'Vitrified Tiles',
        coveredParking: 2, coveredUnParking: 0, sutableFor: 'Family',
        additionalRooms: ['Pooja Room'], trasactionType: 'Resale',
        landmarkHospital: 'KIMS Hospital 3 km', landmarkEducationInstitute: 'ISB Business School 2 km',
        landmarkShoppingCenter: 'Inorbit Mall 4 km', landmarkTransportation: 'Gachibowli Metro 1 km',
        landmarkCommercialHub: 'HITEC City 3 km',
        amenitiesDetails: [{ name: 'Swimming Pool', count: 1 }, { name: 'Gym', count: 1 }, { name: 'Badminton Court', count: 2 }, { name: 'CCTV Surveillance', count: 1 }],
        furnishingDetails: [{ name: 'AC', count: 3 }, { name: 'Geyser', count: 2 }],
        aboutProperty: "My Home Aura — ultra-luxurious living in the heart of Hyderabad's IT corridor.",
        uploadedPaths: img(PROPERTY_IMG.hyderabadMadhapurHighrise), isExclusive: false, isFeatured: true,
        createAt: daysAgo(12), updatedAt: daysAgo(1),
    },
    {
        propertyID: 'kohinoor-central-park-3bhk-hinjewadi-sale-pune',
        title: 'Kohinoor Central Park', listingType: 'sale', buildingType: 'Apartment',
        propertyType: 'Residential', possessionStatus: 'Ready To Move',
        price: '13500000', priceNumber: 13500000,
        area: '1750', areaNumber: 1750, areaCarpet: '1500', areaCarpetNumber: 1500,
        location: 'Hinjewadi Phase 2', city: 'Pune', postalCode: '411057',
        houseType: '3 BHK', bathsType: '3', floorNumber: '11', floorNumberNumber: 11,
        towerBlock: 'C', totalFloorCount: '22', ageProperty: '0-2',
        furnishingStatus: 'Semi-Furnished', facing: 'North East', view: 'Hills View',
        balcony: '2', powerBackup: 'Full', flooring: 'Vitrified Tiles',
        coveredParking: 2, coveredUnParking: 0, sutableFor: 'Family',
        additionalRooms: ['Pooja Room', 'Study Room'], trasactionType: 'Resale',
        landmarkHospital: 'Sahyadri Hospital 4 km', landmarkEducationInstitute: 'MIT World Peace University 5 km',
        landmarkShoppingCenter: 'Westend Mall 3 km', landmarkTransportation: 'Hinjewadi BRTS 500 m',
        landmarkCommercialHub: 'Rajiv Gandhi IT Park 1 km',
        amenitiesDetails: [{ name: 'Swimming Pool', count: 1 }, { name: 'Gym', count: 1 }, { name: 'Clubhouse', count: 1 }, { name: 'Jogging Track', count: 1 }],
        furnishingDetails: [{ name: 'AC', count: 3 }, { name: 'Geyser', count: 2 }],
        aboutProperty: "Kohinoor Central Park — premium residences in Pune's IT capital, Hinjewadi.",
        uploadedPaths: img(PROPERTY_IMG.puneSkylineWestin), isExclusive: false, isFeatured: true,
        createAt: daysAgo(28), updatedAt: daysAgo(4),
    },

    // ─── New listings ──────────────────────────────────────────────────────────
    {
        propertyID: 'sobha-dream-acres-2-bhk-whitefield-sale-bangalore',
        title: 'Sobha Dream Acres', listingType: 'sale', buildingType: 'Apartment',
        propertyType: 'Residential', possessionStatus: 'Ready To Move',
        price: '8900000', priceNumber: 8900000,
        area: '1180', areaNumber: 1180, areaCarpet: '980', areaCarpetNumber: 980,
        location: 'Whitefield', city: 'Bangalore', postalCode: '560066',
        houseType: '2 BHK', bathsType: '2', floorNumber: '6', floorNumberNumber: 6,
        towerBlock: 'D4', totalFloorCount: '14', ageProperty: '2-4',
        furnishingStatus: 'Semi-Furnished', facing: 'North', view: 'Clubhouse View',
        balcony: '2', powerBackup: 'Full', flooring: 'Vitrified Tiles',
        coveredParking: 1, coveredUnParking: 0, sutableFor: 'Family',
        additionalRooms: ['Study Room'], trasactionType: 'Resale',
        landmarkHospital: 'Columbia Asia Hospital 2 km', landmarkEducationInstitute: 'Vydehi School 1.5 km',
        landmarkShoppingCenter: 'Phoenix Marketcity 4 km', landmarkTransportation: 'Whitefield Metro 2 km',
        landmarkCommercialHub: 'ITPL Tech Park 3 km',
        amenitiesDetails: [{ name: 'Swimming Pool', count: 3 }, { name: 'Gym', count: 1 }, { name: 'Clubhouse', count: 1 }, { name: 'Cricket Pitch', count: 1 }, { name: 'Amphitheatre', count: 1 }],
        furnishingDetails: [{ name: 'Wardrobe', count: 2 }, { name: 'Modular Kitchen', count: 1 }],
        aboutProperty: 'Sobha Dream Acres is one of the largest gated communities in Whitefield, close to the ITPL tech corridor.',
        uploadedPaths: img(PROPERTY_IMG.bangaloreValmarkApas, PROPERTY_IMG.interiorLivingRoom1), isExclusive: false, isFeatured: true,
        createAt: daysAgo(18), updatedAt: daysAgo(1),
    },
    {
        propertyID: 'prestige-falcon-city-3-bhk-kanakapura-road-rent-bangalore',
        title: 'Prestige Falcon City', listingType: 'rent', buildingType: 'Apartment',
        propertyType: 'Residential', possessionStatus: 'Ready To Move',
        price: '48000', priceNumber: 48000,
        area: '1620', areaNumber: 1620, areaCarpet: '1380', areaCarpetNumber: 1380,
        location: 'Kanakapura Road', city: 'Bangalore', postalCode: '560062',
        houseType: '3 BHK', bathsType: '3', floorNumber: '14', floorNumberNumber: 14,
        towerBlock: 'Wing 2', totalFloorCount: '20', ageProperty: '2-4',
        furnishingStatus: 'Fully Furnished', facing: 'West', view: 'Park View',
        balcony: '2', powerBackup: 'Full', flooring: 'Vitrified Tiles',
        coveredParking: 1, coveredUnParking: 0, sutableFor: 'Family',
        additionalRooms: ['Pooja Room'], trasactionType: 'Rent',
        landmarkHospital: 'Fortis Hospital 3 km', landmarkEducationInstitute: 'Delhi Public School 2 km',
        landmarkShoppingCenter: 'Vega City Mall 3.5 km', landmarkTransportation: 'Yelachenahalli Metro 4 km',
        amenitiesDetails: [{ name: 'Swimming Pool', count: 1 }, { name: 'Gym', count: 1 }, { name: 'Multiplex', count: 1 }, { name: 'Amusement Park', count: 1 }],
        furnishingDetails: [{ name: 'AC', count: 3 }, { name: 'Wardrobe', count: 3 }, { name: 'Refrigerator', count: 1 }, { name: 'Washing Machine', count: 1 }, { name: 'Sofa Set', count: 1 }],
        aboutProperty: 'Spacious fully-furnished 3 BHK in Prestige Falcon City, Bangalore’s largest township with an in-house multiplex and amusement park.',
        uploadedPaths: img(PROPERTY_IMG.bangalorePashminaWaterfront), isExclusive: false, isFeatured: false,
        createAt: daysAgo(9), updatedAt: daysAgo(1),
    },
    {
        propertyID: 'prestige-tech-park-one-office-outer-ring-road-sale-bangalore',
        title: 'Prestige Tech Park One', listingType: 'sale', buildingType: 'Office',
        propertyType: 'Commercial', possessionStatus: 'Ready To Move',
        price: '25000000', priceNumber: 25000000,
        area: '2200', areaNumber: 2200, areaCarpet: '2000', areaCarpetNumber: 2000,
        location: 'Outer Ring Road', city: 'Bangalore', postalCode: '560103',
        houseType: 'N/A', bathsType: '2', floorNumber: '7', floorNumberNumber: 7,
        towerBlock: 'Tower A', totalFloorCount: '15', ageProperty: '2-4',
        furnishingStatus: 'Semi-Furnished', facing: 'East', view: 'City View',
        balcony: '0', powerBackup: 'Full', flooring: 'Vitrified Tiles',
        coveredParking: 4, coveredUnParking: 2, sutableFor: 'Commercial',
        additionalRooms: ['Conference Room', 'Server Room'], trasactionType: 'Resale',
        landmarkCommercialHub: 'Bellandur IT Corridor 1 km', landmarkTransportation: 'Outer Ring Road Bus Stop 300 m',
        amenitiesDetails: [{ name: 'Central AC', count: 1 }, { name: 'Backup Power', count: 1 }, { name: 'Cafeteria', count: 1 }, { name: '24/7 Security', count: 1 }],
        furnishingDetails: [],
        aboutProperty: 'Grade-A office floor plate in Prestige Tech Park, minutes from Bangalore’s Outer Ring Road IT corridor.',
        uploadedPaths: img(PROPERTY_IMG.officeGeneric1), isExclusive: false, isFeatured: false,
        createAt: daysAgo(20), updatedAt: daysAgo(3),
    },
    {
        propertyID: 'oberoi-sky-city-3-bhk-borivali-sale-mumbai',
        title: 'Oberoi Sky City', listingType: 'sale', buildingType: 'Apartment',
        propertyType: 'Residential', possessionStatus: 'Ready To Move',
        price: '28500000', priceNumber: 28500000,
        area: '1480', areaNumber: 1480, areaCarpet: '1220', areaCarpetNumber: 1220,
        location: 'Borivali East', city: 'Mumbai', postalCode: '400066',
        houseType: '3 BHK', bathsType: '3', floorNumber: '32', floorNumberNumber: 32,
        towerBlock: 'Tower 3', totalFloorCount: '48', ageProperty: '2-4',
        furnishingStatus: 'Unfurnished', facing: 'West', view: 'City View',
        balcony: '2', powerBackup: 'Full', flooring: 'Marble',
        coveredParking: 2, coveredUnParking: 0, sutableFor: 'Family',
        additionalRooms: ['Study Room'], trasactionType: 'Resale',
        landmarkHospital: "Kokilaben Dhirubhai Ambani 6 km", landmarkEducationInstitute: 'Thakur College 3 km',
        landmarkShoppingCenter: 'Growels 101 Mall 2 km', landmarkTransportation: 'Borivali Station 1.5 km',
        landmarkCommercialHub: 'Mindspace Malad 5 km',
        amenitiesDetails: [{ name: 'Swimming Pool', count: 1 }, { name: 'Gym', count: 1 }, { name: 'Sky Lounge', count: 1 }, { name: 'Kids Play Area', count: 1 }],
        furnishingDetails: [],
        aboutProperty: 'Oberoi Sky City offers mall-integrated, high-rise living in the Western Suburbs with panoramic city views.',
        uploadedPaths: img(PROPERTY_IMG.mumbaiApartments1), isExclusive: true, isFeatured: false,
        createAt: daysAgo(22), updatedAt: daysAgo(2),
    },
    {
        propertyID: 'hiranandani-gardens-2-bhk-powai-rent-mumbai',
        title: 'Hiranandani Gardens', listingType: 'rent', buildingType: 'Apartment',
        propertyType: 'Residential', possessionStatus: 'Ready To Move',
        price: '65000', priceNumber: 65000,
        area: '1050', areaNumber: 1050, areaCarpet: '880', areaCarpetNumber: 880,
        location: 'Powai', city: 'Mumbai', postalCode: '400076',
        houseType: '2 BHK', bathsType: '2', floorNumber: '11', floorNumberNumber: 11,
        towerBlock: 'Evita', totalFloorCount: '18', ageProperty: '4-10',
        furnishingStatus: 'Fully Furnished', facing: 'East', view: 'Lake View',
        balcony: '1', powerBackup: 'Full', flooring: 'Vitrified Tiles',
        coveredParking: 1, coveredUnParking: 0, sutableFor: 'Family',
        additionalRooms: [], trasactionType: 'Rent',
        landmarkHospital: 'Hiranandani Hospital 1 km', landmarkEducationInstitute: 'IIT Bombay 3 km',
        landmarkShoppingCenter: 'R City Mall 4 km', landmarkTransportation: 'Powai Bus Depot 500 m',
        landmarkCommercialHub: 'Powai Business District 1 km',
        amenitiesDetails: [{ name: 'Lake Promenade', count: 1 }, { name: 'Gym', count: 1 }, { name: 'Security', count: 1 }],
        furnishingDetails: [{ name: 'AC', count: 2 }, { name: 'Wardrobe', count: 2 }, { name: 'Refrigerator', count: 1 }, { name: 'Sofa Set', count: 1 }],
        aboutProperty: 'Lake-facing 2 BHK in the leafy, self-contained Hiranandani Gardens township next to IIT Bombay and Powai’s office district.',
        uploadedPaths: img(PROPERTY_IMG.mumbaiBuilding1), isExclusive: false, isFeatured: false,
        createAt: daysAgo(6), updatedAt: daysAgo(0),
    },
    {
        propertyID: 'rustomjee-seasons-4-bhk-bandra-kurla-complex-sale-mumbai',
        title: 'Rustomjee Seasons', listingType: 'sale', buildingType: 'Apartment',
        propertyType: 'Residential', possessionStatus: 'Ready To Move',
        price: '95000000', priceNumber: 95000000,
        area: '3400', areaNumber: 3400, areaCarpet: '2950', areaCarpetNumber: 2950,
        location: 'Bandra Kurla Complex', city: 'Mumbai', postalCode: '400051',
        houseType: '4 BHK', bathsType: '4', floorNumber: '40', floorNumberNumber: 40,
        towerBlock: 'Tower 1', totalFloorCount: '52', ageProperty: 'New',
        furnishingStatus: 'Fully Furnished', facing: 'South', view: 'Skyline View',
        balcony: '3', powerBackup: 'Full', flooring: 'Italian Marble',
        coveredParking: 3, coveredUnParking: 0, sutableFor: 'Family',
        additionalRooms: ['Servant Quarter', 'Home Theatre'], trasactionType: 'New Booking',
        landmarkHospital: 'Kohinoor Hospital 3 km', landmarkEducationInstitute: 'Dhirubhai Ambani International School 2 km',
        landmarkShoppingCenter: 'Jio World Drive 2.5 km', landmarkTransportation: 'BKC Metro 1 km',
        landmarkCommercialHub: 'BKC Financial District 500 m',
        amenitiesDetails: [{ name: 'Infinity Pool', count: 1 }, { name: 'Spa', count: 1 }, { name: 'Concierge', count: 1 }, { name: 'Valet Parking', count: 1 }],
        furnishingDetails: [{ name: 'AC', count: 5 }, { name: 'Smart Home', count: 1 }, { name: 'Modular Kitchen', count: 1 }],
        aboutProperty: 'Rustomjee Seasons places you inside Mumbai’s financial nerve centre, BKC, with unobstructed skyline views.',
        uploadedPaths: img(PROPERTY_IMG.mumbaiSkyscraperRailway, PROPERTY_IMG.interiorLivingRoom2), isExclusive: true, isFeatured: true,
        createAt: daysAgo(14), updatedAt: daysAgo(1),
    },
    {
        propertyID: 'godrej-bkc-office-bandra-kurla-complex-sale-mumbai',
        title: 'Godrej BKC', listingType: 'sale', buildingType: 'Office',
        propertyType: 'Commercial', possessionStatus: 'Ready To Move',
        price: '65000000', priceNumber: 65000000,
        area: '3000', areaNumber: 3000, areaCarpet: '2700', areaCarpetNumber: 2700,
        location: 'Bandra Kurla Complex', city: 'Mumbai', postalCode: '400051',
        houseType: 'N/A', bathsType: '3', floorNumber: '12', floorNumberNumber: 12,
        towerBlock: 'Tower B', totalFloorCount: '20', ageProperty: '2-4',
        furnishingStatus: 'Semi-Furnished', facing: 'North', view: 'City View',
        balcony: '0', powerBackup: 'Full', flooring: 'Vitrified Tiles',
        coveredParking: 5, coveredUnParking: 2, sutableFor: 'Commercial',
        additionalRooms: ['Conference Room', 'Reception'], trasactionType: 'Resale',
        landmarkCommercialHub: 'BKC Financial District 200 m', landmarkTransportation: 'BKC Metro 400 m',
        amenitiesDetails: [{ name: 'Central AC', count: 1 }, { name: 'Cafeteria', count: 1 }, { name: '24/7 Security', count: 1 }, { name: 'Backup Power', count: 1 }],
        furnishingDetails: [],
        aboutProperty: 'LEED-certified commercial floor in Godrej BKC, walking distance from Mumbai’s top financial institutions.',
        uploadedPaths: img(PROPERTY_IMG.officeGeneric2), isExclusive: false, isFeatured: false,
        createAt: daysAgo(11), updatedAt: daysAgo(1),
    },
    {
        propertyID: 'aparna-sarovar-zenith-3-bhk-nallagandla-sale-hyderabad',
        title: 'Aparna Sarovar Zenith', listingType: 'sale', buildingType: 'Apartment',
        propertyType: 'Residential', possessionStatus: 'Ready To Move',
        price: '9800000', priceNumber: 9800000,
        area: '1650', areaNumber: 1650, areaCarpet: '1400', areaCarpetNumber: 1400,
        location: 'Nallagandla', city: 'Hyderabad', postalCode: '500019',
        houseType: '3 BHK', bathsType: '3', floorNumber: '10', floorNumberNumber: 10,
        towerBlock: 'C', totalFloorCount: '19', ageProperty: '2-4',
        furnishingStatus: 'Semi-Furnished', facing: 'East', view: 'Lake View',
        balcony: '2', powerBackup: 'Full', flooring: 'Vitrified Tiles',
        coveredParking: 2, coveredUnParking: 0, sutableFor: 'Family',
        additionalRooms: ['Pooja Room', 'Study Room'], trasactionType: 'Resale',
        landmarkHospital: 'Continental Hospital 3 km', landmarkEducationInstitute: 'Oakridge International School 2 km',
        landmarkShoppingCenter: 'Sarath City Capital Mall 4 km', landmarkTransportation: 'Gachibowli 5 km',
        landmarkCommercialHub: 'Financial District 3 km',
        amenitiesDetails: [{ name: 'Swimming Pool', count: 2 }, { name: 'Gym', count: 1 }, { name: 'Clubhouse', count: 1 }, { name: 'Jogging Track', count: 1 }],
        furnishingDetails: [{ name: 'AC', count: 3 }, { name: 'Geyser', count: 2 }],
        aboutProperty: 'Aparna Sarovar Zenith overlooks Nallagandla Lake, minutes from Hyderabad’s Financial District.',
        uploadedPaths: img(PROPERTY_IMG.hyderabadHussainsagar), isExclusive: false, isFeatured: false,
        createAt: daysAgo(16), updatedAt: daysAgo(2),
    },
    {
        propertyID: 'rajapushpa-provincia-villa-kokapet-sale-hyderabad',
        title: 'Rajapushpa Provincia', listingType: 'sale', buildingType: 'Villa',
        propertyType: 'Residential', possessionStatus: 'Under Construction',
        price: '42000000', priceNumber: 42000000,
        area: '4500', areaNumber: 4500, areaCarpet: '4000', areaCarpetNumber: 4000,
        location: 'Kokapet', city: 'Hyderabad', postalCode: '500075',
        houseType: '4 BHK', bathsType: '5', floorNumber: 'G+1', floorNumberNumber: 1,
        towerBlock: 'Villa 42', totalFloorCount: '2', ageProperty: 'New',
        furnishingStatus: 'Unfurnished', facing: 'North East', view: 'Garden View',
        balcony: '4', powerBackup: 'Full', flooring: 'Italian Marble',
        coveredParking: 3, coveredUnParking: 1, sutableFor: 'Family',
        additionalRooms: ['Servant Quarter', 'Home Theatre', 'Pooja Room', 'Private Garden'], trasactionType: 'New Booking',
        landmarkHospital: 'AIG Hospital 4 km', landmarkEducationInstitute: 'Oakridge International School 3 km',
        landmarkShoppingCenter: 'Inorbit Mall 6 km', landmarkTransportation: 'ORR Kokapet Exit 1 km',
        landmarkCommercialHub: 'Financial District 4 km',
        amenitiesDetails: [{ name: 'Private Pool', count: 1 }, { name: 'Clubhouse', count: 1 }, { name: 'Golf Simulator', count: 1 }, { name: '24/7 Security', count: 1 }],
        furnishingDetails: [],
        aboutProperty: 'Gated villa community in Kokapet with private gardens, close to Hyderabad’s upcoming Financial District expansion.',
        uploadedPaths: img(PROPERTY_IMG.hyderabadVillaGreens), isExclusive: true, isFeatured: true,
        createAt: daysAgo(19), updatedAt: daysAgo(3),
    },
    {
        propertyID: 'phoenix-one-hitec-city-office-hitec-city-rent-hyderabad',
        title: 'Phoenix One Hitec City', listingType: 'rent', buildingType: 'Office',
        propertyType: 'Commercial', possessionStatus: 'Ready To Move',
        price: '180000', priceNumber: 180000,
        area: '4000', areaNumber: 4000, areaCarpet: '3600', areaCarpetNumber: 3600,
        location: 'HITEC City', city: 'Hyderabad', postalCode: '500081',
        houseType: 'N/A', bathsType: '4', floorNumber: '5', floorNumberNumber: 5,
        towerBlock: 'Wing C', totalFloorCount: '12', ageProperty: '2-4',
        furnishingStatus: 'Fully Furnished', facing: 'West', view: 'City View',
        balcony: '0', powerBackup: 'Full', flooring: 'Raised Access Flooring',
        coveredParking: 8, coveredUnParking: 4, sutableFor: 'Commercial',
        additionalRooms: ['Conference Room', 'Server Room', 'Cafeteria'], trasactionType: 'Rent',
        landmarkCommercialHub: 'HITEC City IT Corridor 300 m', landmarkTransportation: 'Hitec City Metro 600 m',
        amenitiesDetails: [{ name: 'Central AC', count: 1 }, { name: 'Backup Power', count: 1 }, { name: 'High-Speed Elevators', count: 4 }, { name: '24/7 Security', count: 1 }],
        furnishingDetails: [],
        aboutProperty: 'Plug-and-play office floor in Phoenix One, right in the middle of Hyderabad’s HITEC City IT corridor.',
        uploadedPaths: img(PROPERTY_IMG.officeGeneric1), isExclusive: false, isFeatured: false,
        createAt: daysAgo(8), updatedAt: daysAgo(0),
    },
    {
        propertyID: 'kolte-patil-life-republic-2-bhk-wagholi-rent-pune',
        title: 'Kolte Patil Life Republic', listingType: 'rent', buildingType: 'Apartment',
        propertyType: 'Residential', possessionStatus: 'Ready To Move',
        price: '22000', priceNumber: 22000,
        area: '980', areaNumber: 980, areaCarpet: '820', areaCarpetNumber: 820,
        location: 'Wagholi', city: 'Pune', postalCode: '412207',
        houseType: '2 BHK', bathsType: '2', floorNumber: '4', floorNumberNumber: 4,
        towerBlock: 'E7', totalFloorCount: '11', ageProperty: '2-4',
        furnishingStatus: 'Semi-Furnished', facing: 'South', view: 'Garden View',
        balcony: '1', powerBackup: 'Partial', flooring: 'Vitrified Tiles',
        coveredParking: 1, coveredUnParking: 0, sutableFor: 'Family',
        additionalRooms: [], trasactionType: 'Rent',
        landmarkHospital: 'Manipal Hospital 3 km', landmarkEducationInstitute: 'Vishwakarma University 2 km',
        landmarkShoppingCenter: 'Phoenix Marketcity 6 km', landmarkTransportation: 'Wagholi Bypass 1 km',
        landmarkCommercialHub: 'EON IT Park 5 km',
        amenitiesDetails: [{ name: 'Swimming Pool', count: 1 }, { name: 'Gym', count: 1 }, { name: 'Amphitheatre', count: 1 }],
        furnishingDetails: [{ name: 'Wardrobe', count: 2 }, { name: 'Modular Kitchen', count: 1 }],
        aboutProperty: 'Life Republic is Pune’s largest integrated township, offering resort-style amenities on the Pune-Ahmednagar Highway.',
        uploadedPaths: img(PROPERTY_IMG.puneViewParvatiHill), isExclusive: false, isFeatured: false,
        createAt: daysAgo(5), updatedAt: daysAgo(0),
    },
    {
        propertyID: 'amanora-park-town-3-bhk-hadapsar-sale-pune',
        title: 'Amanora Park Town', listingType: 'sale', buildingType: 'Apartment',
        propertyType: 'Residential', possessionStatus: 'Ready To Move',
        price: '15800000', priceNumber: 15800000,
        area: '1720', areaNumber: 1720, areaCarpet: '1480', areaCarpetNumber: 1480,
        location: 'Hadapsar', city: 'Pune', postalCode: '411028',
        houseType: '3 BHK', bathsType: '3', floorNumber: '15', floorNumberNumber: 15,
        towerBlock: 'Adreno', totalFloorCount: '25', ageProperty: '0-2',
        furnishingStatus: 'Semi-Furnished', facing: 'East', view: 'City View',
        balcony: '2', powerBackup: 'Full', flooring: 'Vitrified Tiles',
        coveredParking: 2, coveredUnParking: 0, sutableFor: 'Family',
        additionalRooms: ['Study Room'], trasactionType: 'New Booking',
        landmarkHospital: 'Noble Hospital 2 km', landmarkEducationInstitute: 'Symbiosis 4 km',
        landmarkShoppingCenter: 'Amanora Mall 500 m', landmarkTransportation: 'Hadapsar Railway 3 km',
        landmarkCommercialHub: 'Magarpatta Cybercity 4 km',
        amenitiesDetails: [{ name: 'Swimming Pool', count: 1 }, { name: 'Gym', count: 1 }, { name: 'Clubhouse', count: 1 }, { name: 'Skating Rink', count: 1 }],
        furnishingDetails: [{ name: 'AC', count: 2 }, { name: 'Modular Kitchen', count: 1 }],
        aboutProperty: 'Amanora Park Town is a self-sufficient township in Hadapsar with its own mall, school and cyber park.',
        uploadedPaths: img(PROPERTY_IMG.puneSkylineWestin), isExclusive: false, isFeatured: true,
        createAt: daysAgo(13), updatedAt: daysAgo(1),
    },
    {
        propertyID: 'eon-free-zone-office-kharadi-rent-pune',
        title: 'EON Free Zone', listingType: 'rent', buildingType: 'Office',
        propertyType: 'Commercial', possessionStatus: 'Ready To Move',
        price: '150000', priceNumber: 150000,
        area: '3500', areaNumber: 3500, areaCarpet: '3150', areaCarpetNumber: 3150,
        location: 'Kharadi', city: 'Pune', postalCode: '411014',
        houseType: 'N/A', bathsType: '4', floorNumber: '3', floorNumberNumber: 3,
        towerBlock: 'Tower 2', totalFloorCount: '10', ageProperty: '2-4',
        furnishingStatus: 'Fully Furnished', facing: 'North', view: 'City View',
        balcony: '0', powerBackup: 'Full', flooring: 'Vitrified Tiles',
        coveredParking: 6, coveredUnParking: 3, sutableFor: 'Commercial',
        additionalRooms: ['Conference Room', 'Cafeteria'], trasactionType: 'Rent',
        landmarkCommercialHub: 'Kharadi IT Corridor 200 m', landmarkTransportation: 'Kharadi Bypass 500 m',
        amenitiesDetails: [{ name: 'Central AC', count: 1 }, { name: 'Backup Power', count: 1 }, { name: 'Food Court', count: 1 }],
        furnishingDetails: [],
        aboutProperty: 'SEZ-approved office space in EON Free Zone, home to several global IT and BFSI companies in Kharadi.',
        uploadedPaths: img(PROPERTY_IMG.puneOfficeFulcrum), isExclusive: false, isFeatured: false,
        createAt: daysAgo(7), updatedAt: daysAgo(0),
    },
    {
        propertyID: 'm3m-golf-estate-villa-golf-course-extension-road-sale-gurgaon',
        title: 'M3M Golf Estate', listingType: 'sale', buildingType: 'Villa',
        propertyType: 'Residential', possessionStatus: 'Ready To Move',
        price: '68000000', priceNumber: 68000000,
        area: '5200', areaNumber: 5200, areaCarpet: '4700', areaCarpetNumber: 4700,
        location: 'Golf Course Extension Road', city: 'Gurgaon', postalCode: '122018',
        houseType: '4 BHK', bathsType: '5', floorNumber: 'G+2', floorNumberNumber: 2,
        towerBlock: 'Villa 12', totalFloorCount: '3', ageProperty: '2-4',
        furnishingStatus: 'Fully Furnished', facing: 'East', view: 'Golf Course View',
        balcony: '4', powerBackup: 'Full', flooring: 'Italian Marble',
        coveredParking: 4, coveredUnParking: 1, sutableFor: 'Family',
        additionalRooms: ['Servant Quarter', 'Home Theatre', 'Private Garden'], trasactionType: 'Resale',
        landmarkHospital: 'Artemis Hospital 3 km', landmarkEducationInstitute: 'Heritage Xperiential School 2 km',
        landmarkShoppingCenter: 'South Point Mall 3 km', landmarkTransportation: 'Golf Course Ext Road 500 m',
        landmarkCommercialHub: 'Cyber Hub 8 km',
        amenitiesDetails: [{ name: 'Private Pool', count: 1 }, { name: 'Golf Course Access', count: 1 }, { name: 'Concierge', count: 1 }, { name: '24/7 Security', count: 1 }],
        furnishingDetails: [{ name: 'AC', count: 6 }, { name: 'Smart Home', count: 1 }],
        aboutProperty: 'Golf-facing villa in M3M Golf Estate, one of Gurgaon’s most exclusive low-density villa communities.',
        uploadedPaths: img(PROPERTY_IMG.villaTownship, PROPERTY_IMG.interiorLivingRoom1), isExclusive: true, isFeatured: true,
        createAt: daysAgo(21), updatedAt: daysAgo(2),
    },
    {
        propertyID: 'vatika-india-next-2-bhk-sector-82-rent-gurgaon',
        title: 'Vatika India Next', listingType: 'rent', buildingType: 'Apartment',
        propertyType: 'Residential', possessionStatus: 'Ready To Move',
        price: '26000', priceNumber: 26000,
        area: '1100', areaNumber: 1100, areaCarpet: '920', areaCarpetNumber: 920,
        location: 'Sector 82', city: 'Gurgaon', postalCode: '122004',
        houseType: '2 BHK', bathsType: '2', floorNumber: '6', floorNumberNumber: 6,
        towerBlock: 'F3', totalFloorCount: '14', ageProperty: '4-10',
        furnishingStatus: 'Semi-Furnished', facing: 'South', view: 'Green Belt View',
        balcony: '1', powerBackup: 'Full', flooring: 'Vitrified Tiles',
        coveredParking: 1, coveredUnParking: 0, sutableFor: 'Family',
        additionalRooms: [], trasactionType: 'Rent',
        landmarkHospital: 'Park Hospital 3 km', landmarkEducationInstitute: 'GD Goenka School 2 km',
        landmarkShoppingCenter: 'Global Foyer Mall 4 km', landmarkTransportation: 'Dwarka Expressway 1 km',
        landmarkCommercialHub: 'Sector 81 IMT 3 km',
        amenitiesDetails: [{ name: 'Swimming Pool', count: 1 }, { name: 'Gym', count: 1 }, { name: 'Community Hall', count: 1 }],
        furnishingDetails: [{ name: 'Wardrobe', count: 2 }, { name: 'Geyser', count: 2 }],
        aboutProperty: 'Affordable 2 BHK in Vatika India Next, well connected via Dwarka Expressway to Delhi and Cyber City.',
        uploadedPaths: img(PROPERTY_IMG.gurgaonBelvedereTowers), isExclusive: false, isFeatured: false,
        createAt: daysAgo(4), updatedAt: daysAgo(0),
    },
    {
        propertyID: 'emaar-digital-greens-office-sector-61-sale-gurgaon',
        title: 'Emaar Digital Greens', listingType: 'sale', buildingType: 'Office',
        propertyType: 'Commercial', possessionStatus: 'Ready To Move',
        price: '45000000', priceNumber: 45000000,
        area: '3200', areaNumber: 3200, areaCarpet: '2900', areaCarpetNumber: 2900,
        location: 'Sector 61', city: 'Gurgaon', postalCode: '122102',
        houseType: 'N/A', bathsType: '3', floorNumber: '9', floorNumberNumber: 9,
        towerBlock: 'Tower 1', totalFloorCount: '18', ageProperty: '2-4',
        furnishingStatus: 'Semi-Furnished', facing: 'North', view: 'City View',
        balcony: '0', powerBackup: 'Full', flooring: 'Vitrified Tiles',
        coveredParking: 6, coveredUnParking: 2, sutableFor: 'Commercial',
        additionalRooms: ['Conference Room', 'Reception'], trasactionType: 'Resale',
        landmarkCommercialHub: 'Golf Course Extension Road 1 km', landmarkTransportation: 'Sohna Road 2 km',
        amenitiesDetails: [{ name: 'Central AC', count: 1 }, { name: 'Backup Power', count: 1 }, { name: 'Food Court', count: 1 }, { name: '24/7 Security', count: 1 }],
        furnishingDetails: [],
        aboutProperty: 'Emaar Digital Greens offers modern Grade-A office space along Gurgaon’s Golf Course Extension corridor.',
        uploadedPaths: img(PROPERTY_IMG.gurgaonCorporateTower), isExclusive: false, isFeatured: false,
        createAt: daysAgo(17), updatedAt: daysAgo(2),
    },
    {
        propertyID: 'casagrand-utopia-3-bhk-omr-sholinganallur-sale-chennai',
        title: 'Casagrand Utopia', listingType: 'sale', buildingType: 'Apartment',
        propertyType: 'Residential', possessionStatus: 'Ready To Move',
        price: '10800000', priceNumber: 10800000,
        area: '1580', areaNumber: 1580, areaCarpet: '1340', areaCarpetNumber: 1340,
        location: 'Sholinganallur, OMR', city: 'Chennai', postalCode: '600119',
        houseType: '3 BHK', bathsType: '3', floorNumber: '8', floorNumberNumber: 8,
        towerBlock: 'B2', totalFloorCount: '16', ageProperty: '2-4',
        furnishingStatus: 'Semi-Furnished', facing: 'East', view: 'Garden View',
        balcony: '2', powerBackup: 'Full', flooring: 'Vitrified Tiles',
        coveredParking: 2, coveredUnParking: 0, sutableFor: 'Family',
        additionalRooms: ['Pooja Room'], trasactionType: 'Resale',
        landmarkHospital: 'Global Hospital 3 km', landmarkEducationInstitute: 'Hindustan University 2 km',
        landmarkShoppingCenter: 'Marina Mall 5 km', landmarkTransportation: 'OMR IT Expressway 500 m',
        landmarkCommercialHub: 'Sholinganallur IT Corridor 1 km',
        amenitiesDetails: [{ name: 'Swimming Pool', count: 1 }, { name: 'Gym', count: 1 }, { name: 'Clubhouse', count: 1 }, { name: 'Indoor Games', count: 1 }],
        furnishingDetails: [{ name: 'AC', count: 2 }, { name: 'Modular Kitchen', count: 1 }],
        aboutProperty: 'Casagrand Utopia sits on Chennai’s OMR IT corridor, a short commute from the city’s major tech campuses.',
        uploadedPaths: img(PROPERTY_IMG.chennaiSprCity), isExclusive: false, isFeatured: true,
        createAt: daysAgo(10), updatedAt: daysAgo(1),
    },
    {
        propertyID: 'radiance-mandarin-2-bhk-velachery-rent-chennai',
        title: 'Radiance Mandarin', listingType: 'rent', buildingType: 'Apartment',
        propertyType: 'Residential', possessionStatus: 'Ready To Move',
        price: '24000', priceNumber: 24000,
        area: '1020', areaNumber: 1020, areaCarpet: '860', areaCarpetNumber: 860,
        location: 'Velachery', city: 'Chennai', postalCode: '600042',
        houseType: '2 BHK', bathsType: '2', floorNumber: '5', floorNumberNumber: 5,
        towerBlock: 'A', totalFloorCount: '10', ageProperty: '2-4',
        furnishingStatus: 'Semi-Furnished', facing: 'North', view: 'Street View',
        balcony: '1', powerBackup: 'Partial', flooring: 'Vitrified Tiles',
        coveredParking: 1, coveredUnParking: 0, sutableFor: 'Family',
        additionalRooms: [], trasactionType: 'Rent',
        landmarkHospital: 'Apollo Hospital 3 km', landmarkEducationInstitute: 'Loyola College 5 km',
        landmarkShoppingCenter: 'Phoenix Marketcity 2 km', landmarkTransportation: 'Velachery MRTS 1 km',
        landmarkCommercialHub: 'Tidel Park 4 km',
        amenitiesDetails: [{ name: 'Lift', count: 2 }, { name: 'Security', count: 1 }, { name: 'Power Backup', count: 1 }],
        furnishingDetails: [{ name: 'Wardrobe', count: 2 }, { name: 'Geyser', count: 2 }],
        aboutProperty: 'Well-connected 2 BHK in Velachery, close to Phoenix Marketcity and the Velachery MRTS station.',
        uploadedPaths: img(PROPERTY_IMG.chennaiPhoenixMarketcity), isExclusive: false, isFeatured: false,
        createAt: daysAgo(3), updatedAt: daysAgo(0),
    },
    {
        propertyID: 'dlf-it-park-office-ramapuram-rent-chennai',
        title: 'DLF IT Park', listingType: 'rent', buildingType: 'Office',
        propertyType: 'Commercial', possessionStatus: 'Ready To Move',
        price: '120000', priceNumber: 120000,
        area: '3000', areaNumber: 3000, areaCarpet: '2700', areaCarpetNumber: 2700,
        location: 'Ramapuram', city: 'Chennai', postalCode: '600089',
        houseType: 'N/A', bathsType: '3', floorNumber: '6', floorNumberNumber: 6,
        towerBlock: 'Block 3', totalFloorCount: '14', ageProperty: '4-10',
        furnishingStatus: 'Fully Furnished', facing: 'East', view: 'City View',
        balcony: '0', powerBackup: 'Full', flooring: 'Raised Access Flooring',
        coveredParking: 5, coveredUnParking: 2, sutableFor: 'Commercial',
        additionalRooms: ['Conference Room', 'Cafeteria'], trasactionType: 'Rent',
        landmarkCommercialHub: 'Guindy Industrial Estate 3 km', landmarkTransportation: 'Ramapuram Bus Terminus 500 m',
        amenitiesDetails: [{ name: 'Central AC', count: 1 }, { name: 'Backup Power', count: 1 }, { name: '24/7 Security', count: 1 }],
        furnishingDetails: [],
        aboutProperty: 'Established IT park in Ramapuram offering fitted-out office floors close to Chennai’s Guindy industrial belt.',
        uploadedPaths: img(PROPERTY_IMG.officeGeneric2), isExclusive: false, isFeatured: false,
        createAt: daysAgo(2), updatedAt: daysAgo(0),
    },
];
